// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID       pgtype.Int4
	Filename pgtype.Text
	Url      pgtype.Text
	Path     pgtype.Text
}
